services:
  grafana:
    image: grafana/grafana
    ports:
      -3000:3000
  prometheus:
    image: prom/prometheus
    ports:
      -9090:9090
  loki:
    image: grafana/loki
    ports:
      -3100:3100
  app:
    image: node/node
    ports:
      -8080:8080